### PR TITLE
fix: correctly transform svg attributes to camelCase

### LINKED ISSUE #14: inline-react-svg not working on icons properly?
### Describe the bug

> How does the program work in its current state? A clear and concise description of what you expected to happen.

After installing an app and going to Dahsboard with demo account, I see lots of errors similar to this one:

> Warning: Invalid DOM property `fill-rule`. Did you mean `fillRule`?

### Steps to reproduce

Install and start app with:

> git clone --depth=1 git@github.com:dwarvesf/nextjs-boilerplate.git my-project-name
> cd my-project-name
> yarn install
> yarn dev

Open http://localhost:3000/ and login with demo account

### Expected behaviour

Errors should not be present, `fillRule` should be generated instead of `fill-rule`.

### Environment

You may write here the specifications like the version of the project, operating system, or hardware if applicable.

**Desktop (please complete the following information):**
 - MacOS 12.5.1
 - Chrome

I tried to debug it and inside that plugin found transformSvg which does that

> // converts
> // `<svg stroke-width="5">`
> // to
> // `<svg strokeWidth="5">`
> // don't convert any custom data-* or aria-* attributes just wrap in quotes

but it's not triggered
Looking further I found this condition, that supposedly executes that transform: 

> node.callee.name === 'require'

I still debugging it, but seems it only works on svg import, and not by passing content with:

> babel.transform(content

Maybe something had changed, or was this error present before?

### PR DESCRIPTION
**Pull request by tuanddd**
#### What's this PR do?

- [x] Use a local plugin to correctly transform svg attributes to React's camelCase notion

#### What are the relevant Git tickets?
- None, this resolves #14 

### Screenshots
|Before|After|
|---|---|
|Xnapper-2022-08-30-14 33 22|Xnapper-2022-08-30-14 33 01|

#### Any background context you want to provide? (if appropriate)
After some testing I notice that the `babel-plugin-inline-react-svg` is actually not being triggered, what we are currently doing right now is just passing the svg content to babel's standard `transform` function => So I remove the plugin altogether and write another plugin myself which does only one job (the transformation code is still copied from the inline plugin though so credit to them)

### CODE REVIEW

File: plugins/svg-attr-camelize.js [hunk 1]
```diff
@@ -0,0 +1,82 @@
+const { declare } = require('@babel/helper-plugin-utils')
```
Comment (zlatanpham) [inline plugins/svg-attr-camelize.js:1]: Can we move it inside `/scripts` folder?

**Review by zlatanpham — APPROVED** [review]
Great work 👍. Just left one suggestion.
